export const paddingXApplication = "px-5 md:px-12 lg:px-24 xl:px-80";

/// Constant Code Level Skill
export const CODE_LEVEL_ADVANCE = "LEVEL_SKILL_ADVANCE";
export const CODE_LEVEL_INTERMEDIATE = "LEVEL_SKILL_INTERMEDIATE";
export const CODE_LEVEL_BASIC = "LEVEL_SKILL_BASIC";
export const CODE_LEVEL_BEGINNER = "LEVEL_SKILL_BEGINNER";

/// Constant Code Web Template
export const CODE_TEMPLATE_WEB_WATANASA = "KODE_TEMPLATE_WEB_WATANASA";
export const CODE_TEMPLATE_WEB_NARAAI = "KODE_TEMPLATE_WEB_NARAAI";
export const CODE_TEMPLATE_WEB_HOSHIRU = "KODE_TEMPLATE_WEB_HOSHIRU";
export const CODE_TEMPLATE_WEB_YAMAKO = "KODE_TEMPLATE_WEB_YAMAKO";
export const CODE_TEMPLATE_WEB_SUGISAWA = "KODE_TEMPLATE_WEB_SUGISAWA";

export const baseAPIURL = `${process.env.NEXT_PUBLIC_BASEAPIURL}`;
